### ISSUE TITLE
训练代码

### ISSUE THREAD

**Issue by zhuwenxing** [YOUSIKI/StyleBank#1]
您好，请问可以开源相关的训练代码吗？

**Comment by YOUSIKI** [comment]
我准备在暑假完善代码，现在只是准备了用于课程报告的部分，期末季比较忙感谢理解 😊

**Comment by zhuwenxing** [comment]
我查了其他的stylebank仓库的代码，不能很好的理解encoder-decoder分支和stylized分支的交替训练。

**Comment by YOUSIKI** [comment]
我只是照葫芦画瓢而已，233

**Comment by zhuwenxing** [comment]
因为看到已经有训练好的模型参数了，这些参数应该通过训练得到的吧？如果训练代码只是不整洁而已，还是希望可以参考一下。

**Comment by YOUSIKI** [comment]
权重来自别人
